//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderComposition = new HashSet<OrderComposition>();
        }
    
        public string Article { get; set; }
        public string ProductName { get; set; }
        public string EdIzm { get; set; }
        public double Cost { get; set; }
        public string Deliverer { get; set; }
        public string Manufacturer { get; set; }
        public string ProductCategory { get; set; }
        public Nullable<double> CurrentDiscount { get; set; }
        public int AmountStored { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    
        public virtual Deliverers Deliverers { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderComposition> OrderComposition { get; set; }
        public virtual ProductCategories ProductCategories { get; set; }
    }
}
